### ISSUE TITLE
Add to the ContentDB

### ISSUE THREAD

**Issue by Lemente** [entuland/imaging#1]
Hello
would you consider adding this mod to the ContentDB?
I'd like to be able to add it to collections, and make it accessible to educators.
It makes a great tool for importing floorplans of buildings.
Thank you!

edit: here are some screenshots of how we used imaging in our projects (consider all screenshots CC-BY Thomate & Lemente)

A castle (Boutavent, France). We imported the floorplan provided by the city with a transparent background. We also forked the mod so the nodes would fall like sand.
This quickly gave us clean outlines for the castle.
![screenshot_20240218_213139](https://github.com/user-attachments/assets/5df91f6b-d57e-4508-a53e-1dd2d8e20d7e)
![screenshot_20240410_111535](https://github.com/user-attachments/assets/f3d0437a-5c6e-4994-abcd-05d07049e046)
![screenshot_20240219_123301](https://github.com/user-attachments/assets/f375cffb-1473-4a55-a135-3b2c7d55e9f6)

A participative urban planning project in Maubeuge, France
![screenshot_20221031_194316](https://github.com/user-attachments/assets/178c75aa-657b-4fb9-998a-92123029c901)
![screenshot_20221031_194341](https://github.com/user-attachments/assets/da1170df-1c93-4987-8c4b-9f8a7fef23be)

**Comment by entuland** [comment]
Nice, glad the mod is coming in handy! Great screenshots!

I just added the mod to ContentDB and submitted it for approval.
